### ISSUE TITLE
Typescript wont compile

### ISSUE THREAD

**Issue by NitsanBaleli** [snelsi/useLongPress#1]
typescript is complaining about 

`Argument of type 'number' is not assignable to parameter of type 'SetStateAction<null>'`

...

```
Argument of type 'number' is not assignable to parameter of type 'SetStateAction<null>'.  TS2345

    35 |       holdTime
    36 |     );
  > 37 |     setTimer(timeoutId);
       |              ^
    38 |   }

```

**Comment by snelsi** [comment]
Thank you for your issue!
I am coding in the non-strict version of typescript, so there was no type warning about it on my side.

I fixed it in the last update.
Please, check if it helped on your side and then I will close this issue.

**Comment by NitsanBaleli** [comment]
it now has problems with the generics.
see https://github.com/microsoft/TypeScript/issues/15713#issuecomment-300545248

**Comment by NitsanBaleli** [comment]
problem solved
